NAME_DISPLAY_MAP: dict = {
    "vt_symbol": "Local Code",
    "direction": "Direction",
    "price": "Price",
    "volume": "Order Volume",
    "time": "Execution Time (s)",
    "interval": "Interval Per Round (s)",
    "offset": "Offset",
    "status": "Algorithm Status",
    "traded_price": "Average Traded Price",
    "traded": "Traded Volume",
    "left": "Remaining Volume",
    "order_volume": "Single Order Volume",
    "timer_count": "Current Round Timer",
    "total_count": "Total Timer Count",
    "template_name": "Algorithm Template",
    "display_volume": "Displayed Volume",
    "price_add": "Order Price Add",
    "step_price": "Grid Spacing",
    "step_volume": "Grid Volume",
    "order_type": "Order Type",
    "active_vt_symbol": "Active Leg Symbol",
    "passive_vt_symbol": "Passive Leg Symbol",
    "spread_up": "Spread Upper Limit",
    "spread_down": "Spread Lower Limit",
    "max_pos": "Maximum Position",
    "start_time": "Start Time",
    "end_time": "End Time",
    "min_volume": "Minimum Order Volume",
    "max_volume": "Maximum Order Volume",
    "volume_change": "Volume Change"
}